### ISSUE TITLE
SRE Documentation additions for more installation info on MCAD and Instascale

### ISSUE THREAD

**Issue by jbusche** [project-codeflare/codeflare-operator#207]
Created issue in MCAD, but asked to move to Operator Issues - so closing [older MCAD issue 537](https://github.com/project-codeflare/multi-cluster-app-dispatcher/issues/537)

The idea is to have a resources/.md file with additional information for SREs

Method to swap out the images when needed
How to change the resources
Maybe how to apply via subscriptions if you don't have the OpenShift UI handy
Cleanup steps

**Comment by jbusche** [comment]
This is what I have on my notes to change MCAD and InstaScale resources.  (NOTE, this only persists under the FAST channel version of ODH 2.0.0)

Edit the CR for either mcads or instascale like this:
```
kubectl edit mcads mcad
or
kubectl edit instascales instascale
```
And then add this under the spec section:
```
  controllerResources:
    limits:
      cpu: "1"
      memory: 1G
    requests:
      cpu: "1"
      memory: 1G
```
