### ISSUE TITLE
Update InstaScale Custom Resource to allow users to specific memory and cpu resources

### ISSUE THREAD

**Issue by anishasthana** [project-codeflare/codeflare-operator#52]

**Comment by anishasthana** [comment]
Ted will be picking this one up

**Comment by tedhtchang** [comment]
@anishasthana My understanding is, currently the [InstaScale CRD](https://github.com/project-codeflare/codeflare-operator/blob/main/config/crd/bases/codeflare.codeflare.dev_instascales.yaml) does not allow specifying resources limit and requests for the InstaScale controller deployment. The asking is to update the CRD to include: 
```
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
```
and update the InstaScale [controller](https://github.com/project-codeflare/codeflare-operator/blob/main/controllers/instascale_controller.go) accordingly.
